# http://travis-ci.org/#!/graphite-project/carbon
language: python
python: 2.7
# sudo is needed to install libboost-python-dev, which is required by pyhash
sudo: required

matrix:
  include:
    - python: pypy
      env:
        - TOXENV=pypy
    - python: 3.4
      env:
        - TOXENV=py34
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOXENV=py37
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOXENV=py37-pyhash
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOXENV=lint

env:
  - TOXENV=py27
  - TOXENV=py27-pyhash
  - TOXENV=py27-twisted13
  - TOXENV=py27-twisted14
  - TOXENV=py27-twisted15
  - TOXENV=py27-twisted16
  - TOXENV=py27-twisted17
  - TOXENV=py27-twisted18
  - TOXENV=lint

before_install:
  - bash -c "if [[ '$TOXENV' == *pyhash* ]]; then sudo apt-get -qq update; sudo apt-get install -y libboost-python-dev; fi"

install:
  - pip install tox

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov
